### ISSUE TITLE
What is the reason for having no-mix-default-named rule?

### ISSUE THREAD

**Issue by gajus** [xjamundx/eslint-plugin-modules#4]
```js
export {
    foo,
    bar
}

export default baz;
```

is a perfectly valid code. What is the rational for having this rule?

**Comment by xjamundx** [comment]
just a preference some people have. we should write some docs though. 

I think some people prefer `export default` only (CommonJS style) and others prefer individual exports only. This rule enforces an either/or approach. Off by default though, because I personally am not sure I'd use it :)

**Comment by xjamundx** [comment]
a
